### PR TITLE
Add Web Demo & Docker environment 

### PR DESCRIPTION
**Pull request by chenxwh**
Hey @kuprel 👋!

Very cool minimal version of dalle-mini!

We implemented a web demo for min-dalle hosted on Replicate, view it here: https://replicate.com/kuprel/min-dalle

This pull request includes the configuration for [Cog](https://github.com/replicate/cog), a tool for packaging models in a standard format. Replicate uses this format to run the model.

We have added some examples in the [gallery](https://replicate.com/kuprel/min-dalle/examples) here, but do [Claim your page here](https://replicate.com/kuprel/min-dalle/claim) so you can edit it, and we'll feature it on our website and tweet about it too. People can also try the model via API when the model page is claimed.

In case you're wondering who I am, I'm from [Replicate](https://replicate.com/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Review by kuprel — COMMENTED** [review]
This is awesome!!  Thanks for making this, so cool.  Is the `predict.py` file necessary?  It's using a function that was removed this morning

**Comment by chenxwh** [comment]
> This is awesome!! Thanks for making this, so cool. Is the `predict.py` file necessary? It's using a function that was removed this morning

Ah yes, it is necessary as the environment is setup by the `cog.yaml` file and then continue to call the `Predictor` in the `predict.py` specified in `cog.yaml`. I wasn't aware it's been removed (I forked last night), I can update it using the current available function, or if you prefer to do it yourself, it is very easy to update and push new version to replicate too :)

**Comment by kuprel** [comment]
Oh cool, yeah I can do it

**Comment by kuprel** [comment]
I modified your `predict.py` to use the current API: https://github.com/kuprel/min-dalle/blob/main/predict.py

I'm not sure how to test that it is working properly though.

**Comment by kuprel** [comment]
I wasn't able to get the docker deamon to run on the GPU machine I ssh into because I didn't have sudo privileges.  And trying it from colab didn't work either.  Are you able to push the updated `predict.py` file by chance?  It would run much faster than the one that's running on replicate right now since the new one uses the setup method to load the model once

**Comment by chenxwh** [comment]
sure thing! Will push it now :) will take some time and I will get you know when it's done

**Comment by chenxwh** [comment]
@kuprel I have pushed the update to Replicate and tested it works :)

**Comment by kuprel** [comment]
The model has been updated to produce a 3x3 grid of images as a single image.  I updated the `predict.py` file in the replicate folder to call the model with a grid size of 3.  The 3x3 grid is a lot more interesting than a single image.  Would love to get this on replicate.  Any chance you could update it?

**Comment by chenxwh** [comment]
Hi yes I can update for you on replicate. Although may I suggest to make use of the replicate UI that will show individual images in a grid automatically? We find this more useful as you can still access each individual image instead of cropping of from the concatenated version. It is very easy to add arbitrary number of images to a list and just return the list in `predict()`. 

Here is an example: https://github.com/chenxwh/dalle-mini/blob/main/predict.py (replicate page looks like this https://replicate.com/borisdayma/dalle-mini)
so essentially, you import and define `ModelOutput` ([line 22](https://github.com/chenxwh/dalle-mini/blob/a36463db283eced84604eb87659bd19c1da7a803/predict.py#L22), of course you do not need the clip_score part), then change the return type ([line 74](https://github.com/chenxwh/dalle-mini/blob/a36463db283eced84604eb87659bd19c1da7a803/predict.py#L74)), and return a list ([line 177](https://github.com/chenxwh/dalle-mini/blob/a36463db283eced84604eb87659bd19c1da7a803/predict.py#L177))

Let me know if this is interesting, and if you like to modify it first I can upload for you afterwards :)

Another thing is that, `cog.yaml` needs to be in the root directory for it to work on replicate - `predict.py` can be put anywhere - in case you'd like to push other models yourself later :)

**Comment by kuprel** [comment]
Thanks!  I just moved `cog.yaml` to the main directory.  That's cool that you can show individual images.  I think I would prefer generating the grid as a single image for now.  It is more efficient than computing multiple images.  But your comment made me realize the grid_size could be a parameter on replicate.  I just updated the `predict.py` file to have grid_size as an input.  Can it be further restricted to only 1, 2, or 3, instead of all integers?

**Comment by chenxwh** [comment]
yes, refer to here https://github.com/replicate/cog/blob/main/docs/python.md#inputkwargs, so with `ge` and `le` you can define the range.

(Also in `cog.yaml` last line to `predict: "replicate/predict.py:Predictor"` to find the corresponding `predict.py` :) )

**Comment by kuprel** [comment]
Cool. I just updated `predict.py` with `ge` and `le` arguments and changed the last line of `cog.yaml` to point to the right place.

**Comment by kuprel** [comment]
Also I just added default arguments for the inputs

**Comment by chenxwh** [comment]
New version is on Replicate, tested seems grid=3 will OOM. Feel free to update the examples!

**Comment by kuprel** [comment]
Awesome!  I didn't realize I could add to the examples gallery.  Cool, doing that now

**Comment by kuprel** [comment]
I wonder why 3x3 grids work on the 12GB gpu in colab and the the 13+GB GPU on replicate

https://colab.research.google.com/github/kuprel/min-dalle/blob/main/min_dalle.ipynb

**Comment by chenxwh** [comment]
yes you can edit the examples of the model page you own (after claiming it)!

We also support running on A100 machines for models need more memory. Just pushed a new version with `cog.yaml` installing torch from stable to support running on A100 (as below), and now it works with grid=3

```
build:
  cuda: "11.0"
  gpu: true
  python_version: "3.8"
  system_packages:
    - "libgl1-mesa-glx"
    - "libglib2.0-0"
  python_packages:
    - "flax==0.5.2"
  run:
    - pip install torch==1.10.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html

predict: "replicate/predict.py:Predictor"
```

**Comment by kuprel** [comment]
Wow cool!  This is great

**Comment by kuprel** [comment]
It blows colab out of the water.  Only 15 seconds for a 3x3 grid.  Wow!  I added the stat to the README

**Comment by kuprel** [comment]
Wow people love running the 3x3 grids on Replicate!  I think a grid size of 4 should work on the A100 too.  A grid size of 3 works with the P100's 16GB of memory and the A100 has at least 40GB.  Wonder if we could do a 4x4 grid?  I updated the predict.py file to allow for grid size of 4 but default to 3.

**Comment by kuprel** [comment]
It would be cool if there was a way to change the `le` value of an input without uploading an entirely new docker image

**Comment by chenxwh** [comment]
I dont think it is possible to change only one file yet, but I can push this new version now :)

**Comment by kuprel** [comment]
Awesome thanks :)

**Comment by chenxwh** [comment]
it's pushed now. I added `Pillow` and `numpy` lib in `cog.yaml` as it complains cannot find them in `min_dalle.py`. Not sure whether this is a new lib that is used in the new version, but all the libs should be listed in `cog.yaml` too :) (some libs are pre-loaded in colab like numpy, but still need to install them in cog)

**Comment by kuprel** [comment]
Wow the 4x4 is fast!  Thanks for doing that.  This is good to know thanks

**Comment by chenxwh** [comment]
Great! yeah it works really well. 

Another thing, We're rolling out [API](https://replicate.com/docs/api) access for all public models so people can use the models on Replicate to build all sorts of weird and wonderful projects (One of our users is feeding air quality sensor data into an image generation model and displaying it in a digital picture frame on their wall!)

We have seen people on Discord requesting API access for your model – are you happy for us to turn that on?

**Comment by kuprel** [comment]
Definitely. I keep getting a CUDA error now. Is that because there's too much traffic?

**Comment by chenxwh** [comment]
What cuda error? If it is OOM then shouldn’t be related to traffic. And If it happens in consecutive runs (not the first) might worth checking whether there’s memory leak - some memory not freed after a prediction
________________________________

**Comment by kuprel** [comment]
CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by kuprel** [comment]
It was running fine when you first pushed it. But now I can't even get it to run once

**Comment by kuprel** [comment]
Now it worked

**Comment by chenxwh** [comment]
yep was about to write you, we rebooted the server and working!

**Pull request merged**
